compile:
	echo "lua53: nothing to do"

run:
	${BINARY} knucleotide.lua-2.lua 0 < /root/data/knucleotide-input25000000.txt

measure:
	/usr/bin/time -v ${BINARY} knucleotide.lua-2.lua 0 < /root/data/knucleotide-input25000000.txt
