compile:
	cp -L binarytrees.node binarytrees.js
run:
	/usr/local/src/node-v7.9.0-linux-x64/bin/node binarytrees.js 21

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v /usr/local/src/node-v7.9.0-linux-x64/bin/node binarytrees.js 21

