compile:
	/usr/local/src/racket-6.8/bin/raco make spectralnorm.racket-3.racket

run:
	/usr/local/src/racket-6.8/bin/racket ./compiled/spectralnorm.racket-3_racket.zo 5500

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v /usr/local/src/racket-6.8/bin/racket ./compiled/spectralnorm.racket-3_racket.zo 5500

