compile:

run:
	php -d memory_limit=1024M knucleotide.php-4.php 0 < /root/data/knucleotide-input25000000.txt

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v php -d memory_limit=1024M knucleotide.php-4.php 0 < /root/data/knucleotide-input25000000.txt

