compile:


run:
	${BINARY} -W0 knucleotide.yarv-7.yarv 0 < /root/data/knucleotide-input25000000.txt

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v ${BINARY} -W0 knucleotide.yarv-7.yarv 0 < /root/data/knucleotide-input25000000.txt

