compile:

run:
	/usr/bin/dart  knucleotide.dart-2.dart 0 < /root/data/knucleotide-input25000000.txt

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v  /usr/bin/dart  knucleotide.dart-2.dart 0 < /root/data/knucleotide-input25000000.txt

