compile:
	echo "python2: nothing to compile"

run:
	${BINARY} -OO spectralnorm.python3-5.py 5500

measure:
	/usr/bin/time -v ${BINARY} -OO spectralnorm.python3-5.py 5500 >> >> /opt/result/${TLANG}.txt
