compile:


measure:
	sudo modprobe msr
	sudo /opt/rapl/main "/usr/local/src/vw8.1.1pul/bin/linuxx86_64/vwlinuxx86_64 /usr/local/src/vw8.1.1pul/image/benchmarks.im -nogui -evaluate \"Tests knucleotide5\" -a 0 < /root/data/knucleotide-input25000000.txt" Smalltalk k-nucleotide

run:
	/usr/local/src/vw8.1.1pul/bin/linuxx86_64/vwlinuxx86_64 /usr/local/src/vw8.1.1pul/image/benchmarks.im -nogui -evaluate \"Tests knucleotide5\" -a 0 < /root/data/knucleotide-input25000000.txt
