compile:
	/usr/local/src/racket-6.8/bin/raco make binarytrees.racket-3.racket

run:
	/usr/local/src/racket-6.8/bin/racket ./compiled/binarytrees.racket-3_racket.zo 21

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v  /usr/local/src/racket-6.8/bin/racket ./compiled/binarytrees.racket-3_racket.zo 21

