compile:


measure:
	/opt/rapl/main "/usr/local/src/vw8.1.1pul/bin/linuxx86_64/vwlinuxx86_64 /usr/local/src/vw8.1.1pul/image/benchmarks.im -nogui -evaluate \"Tests revcomp\" -a 0 < /root/data/revcomp-input25000000.txt" Smalltalk reverse-complement

run:
	/usr/local/src/vw8.1.1pul/bin/linuxx86_64/vwlinuxx86_64 /usr/local/src/vw8.1.1pul/image/benchmarks.im -nogui -evaluate \"Tests revcomp\" -a 0 < /root/data/revcomp-input25000000.txt
