compile:
	cp -L fasta.node-4.node fasta.node-4.js
run:
	/usr/local/src/node-v7.9.0-linux-x64/bin/node fasta.node-4.js 25000000

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v /usr/local/src/node-v7.9.0-linux-x64/bin/node fasta.node-4.js 25000000



