compile:
	echo "lua51: nothing to do"

run:
	${BINARY}  revcomp.lua-2.lua 0 < /root/data/revcomp-input25000000.txt

measure:
	/usr/bin/time -v ${BINARY}  revcomp.lua-2.lua 0 < /root/data/revcomp-input25000000.txt
