compile:

run:
	${BINARY} revcomp.perl-3.perl 0 < /root/data/revcomp-input25000000.txt >> /opt/results/${TLANG}.txt

measure:
	/usr/bin/time -v ${BINARY} revcomp.perl-3.perl 0 < /root/data/revcomp-input25000000.txt >> /opt/measures/${TLANG}.txt
