compile:
	echo "python2: nothing to compile"

run:
	${BINARY} -OO binarytrees.py 21 >> /opt/results/${TLANG}.txt

measure:
	/usr/bin/time -v ${BINARY} -OO binarytrees.py 21 >> /opt/measures/${TLANG}.txt
