compile:
	/usr/bin/go build -o knucleotide.go-6.go_run

run:
	./knucleotide.go-6.go_run 0 < /root/data/knucleotide-input25000000.txt

measure:
	/usr/bin/time -o /opt/measures/${TLANG}.txt -v  ./knucleotide.go-6.go_run 0 < /root/data/knucleotide-input25000000.txt

